### ISSUE TITLE
make fail

### ISSUE THREAD

**Issue by roychen1998** [sifive/freedom-tools#26]
rm -rf obj/x86_64-linux-ubuntu14/build/riscv-gnu-toolchain/build-binutils-newlib/
mkdir -p obj/x86_64-linux-ubuntu14/build/riscv-gnu-toolchain/build-binutils-newlib/
cd obj/x86_64-linux-ubuntu14/build/riscv-gnu-toolchain/build-binutils-newlib/ && CC_FOR_TARGET=riscv64-unknown-elf-gcc /home/roychen/projects/freedom-tools/obj/x86_64-linux-ubuntu14/build/riscv-gnu-toolchain/riscv-binutils/configure \
	--target=riscv64-unknown-elf \
	--host=x86_64-linux-gnu \
	--prefix=/home/roychen/projects/freedom-tools/obj/x86_64-linux-ubuntu14/install/riscv64-unknown-elf-gcc-8.3.0-2019.11.0-preview5-x86_64-linux-ubuntu14 \
	--with-pkgversion="SiFive Binutils 2.32.0-2019.11.0-preview4" \
	--with-bugurl="https://github.com/sifive/freedom-tools/issues" \
	--disable-werror \
	--with-expat=yes  --with-mpc=no --with-mpfr=no --with-gmp=no \
	--disable-gdb \
	--disable-sim \
	--disable-libdecnumber \
	--disable-libreadline \
	CFLAGS="-O2" \
	CXXFLAGS="-O2" &>make-configure.log
make -C obj/x86_64-linux-ubuntu14/build/riscv-gnu-toolchain/build-binutils-newlib/ &>obj/x86_64-linux-ubuntu14/build/riscv-gnu-toolchain/build-binutils-newlib//make-build.log
make -C obj/x86_64-linux-ubuntu14/build/riscv-gnu-toolchain/build-binutils-newlib/ install -j1 install-pdf install-html &>obj/x86_64-linux-ubuntu14/build/riscv-gnu-toolchain/build-binutils-newlib//make-install.log
Makefile:444: recipe for target 'obj/x86_64-linux-ubuntu14/build/riscv-gnu-toolchain/build-binutils-newlib/stamp' failed
make: *** [obj/x86_64-linux-ubuntu14/build/riscv-gnu-toolchain/build-binutils-newlib/stamp] Error 2

**Comment by duchao713** [comment]
Hi roy, how did you fix the issue ?
