### ISSUE TITLE
How to install an application on TockOS

### ISSUE THREAD

**Issue by bling206** [sifive/freedom-tools#35]
Hi SiFive Team

Currently, I could upload the TockOS FW to the HiFive1 board. Since the TockLoader doesn't support HiFive1, how to install an application to HiFive1? Or what function can I use to experience TockOS on HiFive1 

Thank you

**Comment by cgsfv** [comment]
Try to take your question to https://forums.sifive.com/
This is repo is only for building the tools.

**Comment by cgsfv** [comment]
Closing, as is not a Freedom Tools issue.
