### ISSUE TITLE
Openocd for Win32

### ISSUE THREAD

**Issue by seanwang520** [sifive/freedom-tools#42]
Hi, 

I try to build openocd for win32 in ubuntu16.

Within the master branch, the bin/openocd is elf format. 
Which is not execuable in Win32 environment. 

And within 201905 branch ?? 
When set breakpoint in gdb, the openocd failed. 
 
"Accertion failed! 
Program: C:\CCore_IDE_suite_RV\tool-chain\OpenOCD\openocd.exe
File: src/target/riscv/riscv-013.c, Line 2382 

Expression: receive_addr < address + size * count 
"

Thanks for your help.

Sean

**Comment by cgsfv** [comment]
Hi,

We are not really supporting the 32-bit environments, and I do not have a 32-bit environment to test it out.
So if you want to try and build OpenOCD for 32-bit, I suggest you go to https://github.com/riscv/riscv-openocd

**Comment by seanwang520** [comment]
OK, thank you.
