### ISSUE TITLE
in what order should I build the tool? and how should I build it?

### ISSUE THREAD

**Issue by kingstone1927** [sifive/freedom-tools#56]
I wonder if we have any clear instruction on how to build the sifive-freedom-tools? There is several submodules in this repo, so I'm afraid that if I mess up the order of installation, I might have to spend a lot of time troubleshooting.

Thanks in advance

**Comment by cgsfv** [comment]
Don't worry, there should be no chance of missing it up. There are several ways to build the packages, depending on which tools you want to build:
- make all : build all packages
- make toolchain : build the gnu toolchain package (incl. binutils, gdb, gcc, newlib)
- make openocd : build the openocd package
- make qemu : build the qemu package
- ...
