### ISSUE TITLE
Add tag for the 2020.08.2 release

### ISSUE THREAD

**Issue by ilg-ul** [sifive/freedom-tools#72]
According to the public SiFive download page (https://www.sifive.com/software) confirmed by the Releases page of this repo, your latest public release is 'April 2020' from... July 16th(!).

However, in `FreedomStudio-4.7.2.2020-11-3-x86_64-apple-darwin.tar.gz`, I discovered a folder named `riscv64-unknown-elf-gcc-10.1.0-2020.08.2`, which shows there were also some non-public releases in the mean time.

Could you clarify your release strategy?

If there were other releases, could you add tags in this repository, especially for the latest 10.x toolchain, so I can identify the exact commits used for all submodules, and be able to reproduce the build?

**Comment by cgsfv** [comment]
The 2020.08 release is now tagged.

**Comment by ilg-ul** [comment]
Thank you.

Could you add this to your checklist and always tag new releases?

**Comment by cgsfv** [comment]
Will do that.
