### ISSUE TITLE
Does the toolchain/newlib support multithread ?

### ISSUE THREAD

**Issue by duchao713** [sifive/freedom-tools#75]
Is multithread supported by default ? any flag need to be added ? 
Thanks.

**Comment by jim-wilson** [comment]
Threads are supported by default.  You do need to use -pthread when compiling and linking as mentioned in the gcc docs.  If you forget that, then you might get linker errors for missing atomic routines.  You can work around that by using -latomic but -pthread is the preferred solution.  Some thread programs won't work correctly using user mode qemu.   They do work on hardware and system mode qemu.

**Comment by duchao713** [comment]
Thanks Jim for the reply.

One further question: what about the dynamic reentrancy ? should I enable it for riscv by -D__DYNAMIC_REENT__ and rebuild the toochain/libs ?

**Comment by jim-wilson** [comment]
Sorry, I didn't notice that this is a newlib question.  On linux threading is supported of course.  On newlib, threading isn't supported by default as you need some kind of OS support to do the thread scheduling, and it assumes no OS support.  Regular newlib has reentrant calls.  Newlib nano does not.  Threading probably won't work with newlib without some porting work.
