### ISSUE TITLE
Missing multilib support for recent prebuilt toolchain

### ISSUE THREAD

**Issue by mortbopet** [sifive/freedom-tools#81]
For the [december 2020 tools release](https://github.com/sifive/freedom-tools/releases/tag/v2020.12.0), compiling a program using `-march=rv32im -mabi=ilp32` with the `riscv64-unknown-elf` toolchain fails, with the following error:
> `riscv64-unknown-elf-gcc: fatal error: Can't found suitable multilib set for '-march=rv32im'/'-mabi=ilp32' `
> `compilation terminated.`

Tested using the `linux-ubuntu14` and `mingw` binaries.
If using the [August 2020 tools release](https://github.com/sifive/freedom-tools/releases/tag/v2020.08.0) or prior, compilation succeeds, so a regression must have happened in-between.

**Comment by Fighter19** [comment]
During the migration from using the build scripts as submodules back to being a monorepo,
the targets to build have changed:

https://github.com/sifive/freedom-gcc-metal/blob/8dddab9c230ec05c46ff3fdc72393aacb5dd8ed3/Makefile#L53
https://github.com/sifive/freedom-gcc-metal/commit/044f8391e6ab7bd52f41b012541a23b8fbaf57fd

I also require the build without the C extension and as it seems currently the only way to obtain them is to build this by hand.
I'm not entirely sure if this is intended, but it seems so from the looks of it.
