### ISSUE TITLE
GDB build error on RHEL7

### ISSUE THREAD

**Issue by KeithoHimself** [sifive/freedom-tools#85]
The following error occurs when building toolchain-metal on RHEL7 (Red Hat Enterprise Linux Server release 7.9 (Maipo)):

Checking dynamic library usage for: /scratch/build_freedom-tools/freedom-tools/obj/x86_64-linux-centos6/install/riscv64-unknown-elf-gdb-10.1.0-2020.12.8-x86_64-linux-centos6/bin/riscv64-unknown-elf-gdb
  Illegal library used: libncursesw.so.5 => /lib64/libncursesw.so.5 (0x00007f93a8dee000)
  Illegal library used: libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00007f93a8bc4000)
  Illegal library used: liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f93a879a000)
make[2]: *** [/scratch/build_freedom-tools/freedom-tools/obj/x86_64-linux-centos6/build/riscv64-unknown-elf-gdb/build-gdb/build.stamp] Error 1

I am using gcc-11.2.0 to build the toolchain.

**Comment by JACKLIAO0** [comment]
did you resolve it ?

**Comment by KeithoHimself** [comment]
No, I just ignore it.  The gdb that gets build will start up and give a prompt.  I haven't been able to do any further testing.
