### ISSUE TITLE
New release based on a more recent GCC?

### ISSUE THREAD

**Issue by ilg-ul** [sifive/freedom-tools#87]
Could you consider making a new release based on anything newer than the current GCC 10.2?

Currently GCC 10.2 cannot be compiled on Mac OS running on Apple Silicon, support was added via some patches to 10.3 and later.

**Comment by kito-cheng** [comment]
Hmmm, we've private version of freedom tools with newer GCC, but I guess we won't open source that soon.

**Comment by ilg-ul** [comment]
How does this cope with the terms of the GPL?
