### ISSUE TITLE
building by m1 apple

### ISSUE THREAD

**Issue by tinc0709** [sifive/freedom-tools#91]
I tried to build qemu package by using my m1 macbook pro, then I got the built named x86_64.

**Comment by ilg-ul** [comment]
If you mean `qemu-riscv`, there is also a binary for Apple Silicon:

- <https://github.com/xpack-dev-tools/qemu-riscv-xpack/releases/>

**Comment by tinc0709** [comment]
> If you mean `qemu-riscv`, there is also a binary for Apple Silicon:
> 
> * https://github.com/xpack-dev-tools/qemu-riscv-xpack/releases/

thank u bro
